"""baseline existing schema

Revision ID: 25782eb03114
Revises: 
Create Date: 2026-09-12 12:47:00.024497

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '25782eb03114'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
